theme: osuny
_merge: deep
params:
  plausible: rapport2022.pixelis.com
  summary:
    position: hero
  components:
    lightbox:
      disabled: true
  menu:
    home:
      toc:
        disabled: false

  debug:
     productionUrl: "https://rapport2022.pixelis.com"