theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: rapport2022.pixelis.com
  summary:
    position: hero
  image_sizes:
    design_system:
      lightbox:
        disabled: true
  debug:
     productionUrl: "https://rapport2022.pixelis.com"